name: Close All Pull Requests

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: crondaemon/close-pr@v1
      with:
        # Optional. Post a issue comment just before closing a pull request.
        comment: "Closing for a new session!"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
